### ISSUE TITLE
Create a modal

### ISSUE THREAD

**Issue by Midknightsnack** [Midknightsnack/how-to-html#3]
Make a modal with a button that opens it. You can put whatever you want in the modal as long as there is something in it and it is has style added to it.

**Comment by fbecerra07** [comment]
May I be able to work on this issue? I think I am able to design the modal dialog while simultaneously ensuring that the accessibility is preserved for screen reader users, having prior experience in reviewing and modifying web apps that were not fully accessible or had a good accessible user experience via the keyboard.

**Comment by Midknightsnack** [comment]
> May I be able to work on this issue? I think I am able to design the modal dialog while simultaneously ensuring that the accessibility is preserved for screen reader users, having prior experience in reviewing and modifying web apps that were not fully accessible or had a good accessible user experience via the keyboard.

Sure. Go for it.

**Comment by fbecerra07** [comment]
> > May I be able to work on this issue? I think I am able to design the modal dialog while simultaneously ensuring that the accessibility is preserved for screen reader users, having prior experience in reviewing and modifying web apps that were not fully accessible or had a good accessible user experience via the keyboard.
> 
> Sure. Go for it.


Just for clarification, anything can go in the modal, correct? There isn't some theme we need to follow for this small web project?
I think I have most of the focus handling ironed out, so I was beginning to think of what should go within the dialog apart from just the simple "Hello world" thing I have just as a working placeholder.

**Comment by Midknightsnack** [comment]
> > > May I be able to work on this issue? I think I am able to design the modal dialog while simultaneously ensuring that the accessibility is preserved for screen reader users, having prior experience in reviewing and modifying web apps that were not fully accessible or had a good accessible user experience via the keyboard.
> > 
> > 
> > Sure. Go for it.
> 
> Just for clarification, anything can go in the modal, correct? There isn't some theme we need to follow for this small web project? I think I have most of the focus handling ironed out, so I was beginning to think of what should go within the dialog apart from just the simple "Hello world" thing I have just as a working placeholder.

**Comment by Midknightsnack** [comment]
I'm not really requiring anything specific when creating the modal. As long as it looks nice, I don't really have an issue with anything you put in it. If you don't have any ideas for it, maybe your modal can look something like a checkout menu, restaurant menu, or maybe an event page with links on it. 

If you still have questions message me on Discord, my username is Midknight#6920. I'll respond faster on there.

**Comment by fbecerra07** [comment]
Thanks for the clarification and for some pointers. I'll throw something together which should hopefully be original!
I'll make note of your Discord. I figured since this would keep things that pertained to this issue, it would make it easier to keep track of ideas / other additional feedback. 

Thanks!

> I'm not really requiring anything specific when creating the modal. As long as it looks nice, I don't really have an issue with anything you put in it. If you don't have any ideas for it, maybe your modal can look something like a checkout menu, restaurant menu, or maybe an event page with links on it.
> 
> If you still have questions message me on Discord, my username is Midknight#6920. I'll respond faster on there.
