### ISSUE TITLE
Create a table

### ISSUE THREAD

**Issue by Midknightsnack** [Midknightsnack/how-to-html#5]
Using the html table tag, create a table that holds student information. The columns should consist of name, age, grade, and favorite food. The rows should consist of different students and you can include up to 5. Be sure to add style to it with styles.css.

**Comment by 1219aks** [comment]
Hi! Can I please be assigned this issue? Thank you.

**Comment by Midknightsnack** [comment]
> Hi! Can I please be assigned this issue? Thank you.

Sure.
